### ISSUE TITLE
Error Loading plugin

### ISSUE THREAD

**Issue by stingone** [mario-peters/Domoticz-Home-Connect-Plugin#15]
When loading the plugin i get the following errors no matter what i do. i followed the instruction how to install.

`2021-02-09 20:52:50.933 Error: Python Plugin System: (Home Connect Plugin) Module Import failed, exception: 'ModuleNotFoundError'
2021-02-09 20:52:50.933 Error: Python Plugin System: (Home Connect Plugin) Module Import failed: ' Name: sseclient'
2021-02-09 20:52:50.933 Error: Python Plugin System: (Home Connect Plugin) Error Line details not available.
2021-02-09 20:52:51.359 Error: Python Plugin System: (Domoticz-Home-Connect-Plugin) failed to load 'plugin.py', Python Path used was '/home/stingone/domoticz/plugins/Domoticz-Home-Connect-Plugin/:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.8/dist-packages'.`

**Comment by stingone** [comment]
solved :) forgot to install sseclient with sudo. now it works

**Comment by stingone** [comment]
plugin seems to work but when looking in the log daemon log file i see the code below. it also does not update the devices only when manual update via hardware.

`
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stingone/domoticz/plugins/Domoticz-Home-Connect-Plugin/homeconnectSSE.py", line 24, in <module>
    response = requests.post("http://"+sys.argv[2]+":"+sys.argv[3],"haId:"+sys.argv[1],HEADER_JSON)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
`

**Comment by mario-peters** [comment]
did you start de homeconnectsse client?
see the wiki for more information?
