### ISSUE TITLE
Plugin will not start . Get 4 errors lines in domoticz log

### ISSUE THREAD

**Issue by wakuwaku** [mario-peters/Domoticz-Home-Connect-Plugin#18]
Hi,
Any solution for this?

I followed the wiki to install the plugin but when I restart Domoticz I get these 4 errors:

2021-05-26 23:18:52.396 Error: (Home Connect) 'onStart' failed 'TypeError':'string indices must be integers'.
2021-05-26 23:18:52.396 Error: (Home Connect) ----> Line 459 in '/opt/domoticz/plugins/homeconnect/plugin.py', function onStart
2021-05-26 23:18:52.396 Error: (Home Connect) ----> Line 95 in '/opt/domoticz/plugins/homeconnect/plugin.py', function onStart
2021-05-26 23:18:52.396 Error: (Home Connect) ----> Line 91 in '/opt/domoticz/plugins/homeconnect/homeconnecthelper.py', function gethaId

I also don't see devices in domoticz related my diskwasher. And there is no listener started on my chosen port. 

I am using: 
Domoticz Version: 2020.2 (build 12230)
Build Hash: 72d6b26e3-modified
Compile Date: 2020-07-19 07:50:32
dzVents Version: 3.0.11
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

**Comment by Garycooper07** [comment]
Hello, also the same errors. I'm trying tu use it with a Bosch WasherDryer. Does this plugin always maintained ?

**Comment by mario-peters** [comment]
did you start the sseclient?

**Comment by mario-peters** [comment]
I just installed the plugin from scratch.
The error suggests that it could not find the device in home connect.
Did you enter the correct credentials and the client id?

**Comment by marcowork** [comment]
I have the same error 

`2022-10-28 15:07:40.794 Error: Vaatwasser: (Domoticz-Home-Connect-Plugin) failed to load 'plugin.py', Python Path used was '/home/marcowork/domoticz/plugins/Domoticz-Home-Connect-Plugin/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2022-10-28 15:07:40.794 Error: Vaatwasser: Module Import failed, exception: 'ModuleNotFoundError'
2022-10-28 15:07:40.794 Error: Vaatwasser: Module Import failed: ' Name: sseclient'
2022-10-28 15:07:40.794 Error: Vaatwasser: Error Line details not available.
2022-10-28 15:07:40.794 Error: Vaatwasser: Exception traceback:
2022-10-28 15:07:40.794 Error: Vaatwasser: ----> Line 60 in '/home/marcowork/domoticz/plugins/Domoticz-Home-Connect-Plugin/plugin.py'
2022-10-28 15:07:40.794 Error: Vaatwasser: ----> Line 5 in '/home/marcowork/domoticz/plugins/Domoticz-Home-Connect-Plugin/homeconnecthelper.py'`

my dishwasher is not visable in Devices for Domoticz

Also I have no clue how to fill in the Port on the plugin. I used 443

I did install sseclient. not sure how to start it

**Comment by Xavier82** [comment]
Hi, I also have this error in Domoticz 2022.2 running on Raspberry Pi with OS Buster:
2023-03-29 14:21:42.281 Error: Siemens Home Connect: Call to function 'onStart' failed, exception details:
2023-03-29 14:21:42.284 Error: Siemens Home Connect: Traceback (most recent call last):
2023-03-29 14:21:42.284 Error: Siemens Home Connect: File "/home/pi/domoticz/plugins/Domoticz-Home-Connect-Plugin/plugin.py", line 459, in onStart
2023-03-29 14:21:42.284 Error: Siemens Home Connect: _plugin.onStart()
2023-03-29 14:21:42.284 Error: Siemens Home Connect: File "/home/pi/domoticz/plugins/Domoticz-Home-Connect-Plugin/plugin.py", line 95, in onStart
2023-03-29 14:21:42.284 Error: Siemens Home Connect: self.haId = homeconnecthelper.gethaId(self,Parameters["Mode1"],Parameters["Mode4"])
2023-03-29 14:21:42.284 Error: Siemens Home Connect: File "/home/pi/domoticz/plugins/Domoticz-Home-Connect-Plugin/homeconnecthelper.py", line 91, in gethaId
2023-03-29 14:21:42.285 Error: Siemens Home Connect: Domoticz.Debug(key + " --> " + str(item[key]))
2023-03-29 14:21:42.285 Error: Siemens Home Connect: TypeError: string indices must be integers

Can you check on how to fix this?
