### ISSUE TITLE
SingleKeyID compatibility

### ISSUE THREAD

**Issue by Zolee984** [mario-peters/Domoticz-Home-Connect-Plugin#22]
It doesn't work for me with SinglekeyID.  (SingleKeyID is the only option, if you sign up now.) The response of the log in, doesn't contains session id.

**Comment by IanDury** [comment]
I think I have the same issue. Signed up last Friday for SinglekeyID and this is what I see in the SSE log:

`requests.exceptions.InvalidHeader: Invalid return character or leading space in header: Authorization`

And in the Domoticz log:

```
2023-01-22 12:18:43.185 Status: Vaatwasser: Entering work loop.
2023-01-22 12:18:43.185 Status: Vaatwasser: Started.
2023-01-22 12:18:43.395 Status: Vaatwasser: Initialized version 3.2.1, author 'Mario Peters'
2023-01-22 12:18:44.010 Error: Vaatwasser: Call to function 'onStart' failed, exception details:
2023-01-22 12:18:44.010 Error: Vaatwasser: Traceback (most recent call last):
2023-01-22 12:18:44.011 Error: Vaatwasser: File "/opt/domoticz/plugins/Domoticz-Home-Connect-Plugin/plugin.py", line 459, in onStart
2023-01-22 12:18:44.011 Error: Vaatwasser: _plugin.onStart()
2023-01-22 12:18:44.011 Error: Vaatwasser: File "/opt/domoticz/plugins/Domoticz-Home-Connect-Plugin/plugin.py", line 95, in onStart
2023-01-22 12:18:44.011 Error: Vaatwasser: self.haId = homeconnecthelper.gethaId(self,Parameters["Mode1"],Parameters["Mode4"])
2023-01-22 12:18:44.011 Error: Vaatwasser: File "/opt/domoticz/plugins/Domoticz-Home-Connect-Plugin/homeconnecthelper.py", line 91, in gethaId
2023-01-22 12:18:44.011 Error: Vaatwasser: Domoticz.Debug(key + " --> " + str(item[key]))
2023-01-22 12:18:44.011 Error: Vaatwasser: TypeError: string indices must be integers
```

**Comment by Xavier82** [comment]
Same issue here also....

**Comment by Xavier82** [comment]
No update about this?

**Comment by thomasV92** [comment]
Have created a work arround. Updated the plugin file and the plugin helper file. Also introduced a new pre-run file. But could not upload the files to this comment

**Comment by Xavier82** [comment]
Good to hear, could you share the updates files? Or do you have a fork where I can find the updated files?

**Comment by thomasV92** [comment]
https://github.com/thomasV92/Domoticz-Home-Connect-Plugin.git

**Comment by Xavier82** [comment]
Nice job, is it possible to create issue in your repository so we can communicate outside here (Mario Peters repository)?
I see I now need to add client secret and the refresh token.
It's not clear to me how to obtain those......

Can you also explain what has to be done with the file "[Pre-RunScript](https://github.com/thomasV92/Domoticz-Home-Connect-Plugin/blob/master/Pre-RunScript)"

I also created a repository last year for Home-Connect:
[https://github.com/Xavier82/Domoticz-Home-Connect-Plugin](url), but I failed in getting the verification URI and user code to work automated without the involvement/interference of the user

**Comment by thomasV92** [comment]
Sorry for not explaining.

In this case it is not automatic, tried to do it with selenium, but that was not working on raspberry pi.  

So you run the first part of the new script and you get the the URL to confirm manually.  After that you run the second part of the script and get the refresh key.  When the refresh key and the client secrets and client id are added to the hardware portal and than  it works when you have the SSE client running.

Will work on it to add the selenium part to the new python script, to run that on a windows computer and use the output for the hardware part of the domoticz.

**Comment by Xavier82** [comment]
Tried Selenium also but with no luck within Python on Rpi.
Please check my fork, The only thing on Domoticz which has to be done is the validation of the user_code from the validation URI (forward to Home-Connect). After that, everything works. I have it integrated in the python script. With my script there is no need to run seperate files or parts. Also check this:
[https://www.domoticz.com/forum/viewtopic.php?p=313751&hilit=home+connect#p313751](url) as where I have described how it works.
